# -*- coding: utf-8 -*-
"""yupdduk_menu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NiFd9m39K1qmdD9DaYX_prcwb7yreHxk
"""

from urllib.request import urlopen
from bs4 import BeautifulSoup

from time import sleep 

html = urlopen("https://www.yupdduk.com/sub/hotmenu?mode=1")

soup = BeautifulSoup(html,'html.parser')

hotmenu_title = soup.find_all('p',{'class':'mpnone hotmenutitle'})
hotmenu_price = soup.find_all('span',{'class':'hotmenuprice'})
hotmenu_composition = soup.find_all('p',{'class':'hotmenusub'})

hotmenu_title_text = [] 
for i in range(len(hotmenu_title)):
 h = hotmenu_title[i].get_text()
 hotmenu_title_text.append(h)

hotmenu_price_text = [] 
for i in range(len(hotmenu_price)):
 hp = hotmenu_price[i].get_text()
 hotmenu_price_text.append(hp)