# -*- coding: utf-8 -*-
"""yupdduk_menu.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NiFd9m39K1qmdD9DaYX_prcwb7yreHxk
"""
#학생1 
from urllib.request import urlopen
from bs4 import BeautifulSoup

from time import sleep 

html = urlopen("https://www.yupdduk.com/sub/hotmenu?mode=1")

soup = BeautifulSoup(html,'html.parser')

hotmenu_title = soup.find_all('p',{'class':'mpnone hotmenutitle'})
hotmenu_price = soup.find_all('span',{'class':'hotmenuprice'})
hotmenu_composition = soup.find_all('p',{'class':'hotmenusub'})

hotmenu_title_text = [] 
for i in range(len(hotmenu_title)):
 h = hotmenu_title[i].get_text()
 hotmenu_title_text.append(h)

hotmenu_price_text = [] 
for i in range(len(hotmenu_price)):
 hp = hotmenu_price[i].get_text()
 hotmenu_price_text.append(hp)
    
#학생2
hotmenu_composition_text= [] 
for i in range(len(hotmenu_composition)):
 c = hotmenu_composition[i].get_text()
 hotmenu_composition_text.append(c)

setmenu_list = hotmenu_title_text[5:10] 
setmenu_list_composition = hotmenu_composition_text[8:13] 

hotmenu_final = dict(zip(hotmenu_title_text,hotmenu_price_text)) 
setmenu_final = dict(zip(setmenu_list,setmenu_list_composition)) 

menu = input('메뉴를 입력해주세요.> ')
if menu in hotmenu_title_text :
   price = hotmenu_final[menu]
   print(f"가격 : {price} 원")
   if menu in setmenu_list:
      composition = setmenu_final[menu]
      print(f"구성 : {composition}")
else:
  print('메뉴에 없습니다.')
